

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "${PORT}:${PORT}"

    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_USERNAME: ${DB_USERNAME}
      PASSWORD: ${PASSWORD}
      DATABASE: ${DATABASE}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      cookieKey: ${cookieKey}

    depends_on:
      - db
    
    volumes:
      - ./backend:/app

    restart: 
      unless-stopped
    networks:
    - vibra-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vibra-network

  frontend:
    build:
      context: ./frontend

      args:
        VITE_BASE_URL: ${VITE_BASE_URL}

    depends_on:
      - backend
    ports:
      - "4173:4173"
    networks:
      - vibra-network

volumes:
  postgres_data:

networks:
  vibra-network:
