name: Deploy Vite Frontend to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar dependencias
        run: npm ci
        working-directory: frontend

      - name: Compilar frontend
        run: npm run build
        working-directory: frontend
        continue-on-error: false
      
      - name: Verificar contenido de dist
        run: ls -R
        working-directory: frontend/dist

      - name: Subir archivos a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 # ⬅️ actualizado
